// SOV-Login SDK generator — bakes a platform's identity into a ready-to-install
// PHP plugin + README, packaged as a dependency-free (store-only) .zip Buffer.
// Pure Node (crypto + zlib only) so it runs inside the relay with no extra deps.
const crypto = require('crypto');
const zlib = require('zlib');

// ── Minimal store-only ZIP writer (no external lib) ───────────────────────────
function makeZip(files) { // files: [{name, data:Buffer}]
  const chunks = [], central = [];
  let offset = 0;
  const dosTime = 0, dosDate = 0x21; // fixed (no Date.now in relay-safe contexts)
  for (const f of files) {
    const name = Buffer.from(f.name, 'utf8');
    const data = Buffer.isBuffer(f.data) ? f.data : Buffer.from(f.data, 'utf8');
    const crc = crc32(data);
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4); local.writeUInt16LE(0, 6);
    local.writeUInt16LE(0, 8); // method 0 = store
    local.writeUInt16LE(dosTime, 10); local.writeUInt16LE(dosDate, 12);
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(data.length, 18); local.writeUInt32LE(data.length, 22);
    local.writeUInt16LE(name.length, 26); local.writeUInt16LE(0, 28);
    chunks.push(local, name, data);
    const cen = Buffer.alloc(46);
    cen.writeUInt32LE(0x02014b50, 0);
    cen.writeUInt16LE(20, 4); cen.writeUInt16LE(20, 6);
    cen.writeUInt16LE(0, 8); cen.writeUInt16LE(0, 10);
    cen.writeUInt16LE(dosTime, 12); cen.writeUInt16LE(dosDate, 14);
    cen.writeUInt32LE(crc, 16);
    cen.writeUInt32LE(data.length, 20); cen.writeUInt32LE(data.length, 24);
    cen.writeUInt16LE(name.length, 28);
    cen.writeUInt32LE(offset, 42);
    central.push(cen, name);
    offset += local.length + name.length + data.length;
  }
  const centralBuf = Buffer.concat(central);
  const centralStart = offset;
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(files.length, 8); end.writeUInt16LE(files.length, 10);
  end.writeUInt32LE(centralBuf.length, 12);
  end.writeUInt32LE(centralStart, 16);
  return Buffer.concat([...chunks, centralBuf, end]);
}
const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xEDB88320 ^ (c >>> 1) : c >>> 1; t[n] = c >>> 0; }
  return t;
})();
function crc32(buf) { let c = 0xFFFFFFFF; for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xFF] ^ (c >>> 8); return (c ^ 0xFFFFFFFF) >>> 0; }

// ── The generated, pre-wired PHP plugin ───────────────────────────────────────
function phpPlugin({ domain, platformId, callbackSecret, returnUrl, relays, nowIso }) {
  const relayArr = relays.map(r => `'${r}'`).join(', ');
  return `<?php
/**
 * SOV Login — auto-generated plugin for ${domain}
 * Generated by the SOV Network relay on ${nowIso}. Do NOT edit the constants
 * below — they wire this file to YOUR platform. Just drop this file on your
 * server and call its two methods from your login flow.
 *
 * SECURITY: this file contains your platform's callback secret. Keep it on your
 * server only. Do not commit it to a public repo or serve its source over HTTP.
 *
 * INSTALL (3 steps):
 *   1. Upload this file (sov-login.php) into your web root, next to your login page.
 *   2. On your "Sign in with SOV" button, call:  SovLogin::initiate();
 *   3. Point your callback page (return_url) at:  $data = SovLogin::handleCallback();
 *      — on success $data['sovereign_id'] is the verified citizen. Create their session.
 */
define('SOV_PLATFORM_ID',     '${platformId}');
define('SOV_CALLBACK_SECRET', '${callbackSecret}');
define('SOV_RETURN_URL',      '${returnUrl}');
$SOV_RELAYS = [${relayArr}];

class SovLogin {
  /** Start a login: ask a relay to open an app-flow session, then redirect/show the pairing code. */
  static function initiate() {
    global $SOV_RELAYS;
    $payload = json_encode(['platform_id' => SOV_PLATFORM_ID, 'return_url' => SOV_RETURN_URL]);
    foreach ($SOV_RELAYS as $ip) {
      $ch = curl_init("http://$ip/sov-login/initiate-app");
      curl_setopt_array($ch, [CURLOPT_POST=>1, CURLOPT_POSTFIELDS=>$payload,
        CURLOPT_HTTPHEADER=>['Content-Type: application/json'], CURLOPT_RETURNTRANSFER=>1, CURLOPT_TIMEOUT=>8]);
      $res = curl_exec($ch); $code = curl_getinfo($ch, CURLINFO_HTTP_CODE); curl_close($ch);
      if ($code === 200) { return json_decode($res, true); } // { session_id, pairing_code, ... }
    }
    throw new Exception('No SOV relay reachable');
  }

  /** Call from your return_url handler. Verifies the relay's HMAC and returns the callback body. */
  static function handleCallback() {
    $raw = file_get_contents('php://input');
    $sig = isset($_SERVER['HTTP_X_SOV_CALLBACK_HMAC']) ? $_SERVER['HTTP_X_SOV_CALLBACK_HMAC'] : '';
    $calc = hash_hmac('sha256', $raw, SOV_CALLBACK_SECRET); // key = literal hex secret, raw body
    if (!$sig || !hash_equals($calc, $sig)) { http_response_code(401); echo 'invalid signature'; exit; }
    $data = json_decode($raw, true);
    if (!is_array($data)) { http_response_code(400); echo 'bad payload'; exit; }
    http_response_code(200); echo 'ok';
    return $data; // includes 'sovereign_id' (verified citizen), 'event', etc.
  }
}
`;
}

function readme({ domain, platformId, nowIso }) {
  return `SOV Login — installation package for ${domain}
Generated ${nowIso}

This package wires SOV Login into your website. Everything is pre-configured —
there is nothing to copy or paste.

WHAT'S INSIDE
  sov-login.php   Your ready-to-use plugin (your platform id, secret, callback
                  URL and relay list are already baked in).
  README.txt      This file.

INSTALL (3 steps)
  1. Extract this zip.
  2. Upload sov-login.php to your web root (the same folder as your login page).
  3. In your login page, add a "Sign in with SOV" button that calls:
         require_once 'sov-login.php';
         $session = SovLogin::initiate();   // shows the citizen a pairing code
     And in your callback page (the return URL you registered):
         require_once 'sov-login.php';
         $data = SovLogin::handleCallback(); // verifies + returns the citizen
         // $data['sovereign_id'] is the logged-in citizen — start their session.

NEW VISITORS (no SOV app yet)
  The SOV-Login challenge response includes a "download_url". Render it next to the
  "Sign in with SOV" QR as a small "New to SOV? Scan to download" QR — a visitor with
  no app scans it, lands on the device-detected download page, installs SOV, then
  signs in, no dead ends. It is a download page/mirror, NEVER a node address.

SECURITY
  sov-login.php contains your platform secret. Keep it on your server. Do NOT
  commit it to a public repo or let its source be downloaded over the web.

Platform ID: ${platformId}
`;
}

function generateBundle({ domain, platformId, callbackSecret, returnUrl, relays, nowIso }) {
  const php = phpPlugin({ domain, platformId, callbackSecret, returnUrl, relays, nowIso });
  const rd = readme({ domain, platformId, nowIso });
  return makeZip([{ name: 'sov-login.php', data: php }, { name: 'README.txt', data: rd }]);
}

module.exports = { generateBundle, makeZip };

